"""del_addTest_3

Revision ID: 062a8fb1bf34
Revises: 5a0b57942629
Create Date: 2023-04-03 15:47:30.173903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062a8fb1bf34'
down_revision = '5a0b57942629'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
