"""first

Revision ID: 2d3432c7f4a4
Revises: 
Create Date: 2023-04-03 14:27:16.697142

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2d3432c7f4a4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
