"""addTest_1

Revision ID: 467209e653f6
Revises: df6ac493068d
Create Date: 2023-04-03 15:42:49.020125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467209e653f6'
down_revision = 'df6ac493068d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_table', sa.Column('testCol', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building_table', 'testCol')
    # ### end Alembic commands ###
