"""migr

Revision ID: 48fdc78f2e8f
Revises: 00ec545a23c4
Create Date: 2023-04-03 15:04:04.498781

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "48fdc78f2e8f"
down_revision = "00ec545a23c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
