"""del_addTest_3

Revision ID: 5a0b57942629
Revises: f82a15ce19c7
Create Date: 2023-04-03 15:47:14.074032

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5a0b57942629"
down_revision = "f82a15ce19c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
