"""del_addTest_4

Revision ID: 736bae831523
Revises: 9de09ae33688
Create Date: 2023-04-03 15:48:44.193787

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "736bae831523"
down_revision = "9de09ae33688"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("building_table", "testCol")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "building_table",
        sa.Column(
            "testCol", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
