"""del_addTest_1

Revision ID: 73c971839003
Revises: 467209e653f6
Create Date: 2023-04-03 15:43:49.859335

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "73c971839003"
down_revision = "467209e653f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
