"""addTest

Revision ID: df6ac493068d
Revises: 48fdc78f2e8f
Create Date: 2023-04-03 15:40:16.884696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6ac493068d'
down_revision = '48fdc78f2e8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building_table', sa.Column('testCol', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'building_table', ['testCol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'building_table', type_='unique')
    op.drop_column('building_table', 'testCol')
    # ### end Alembic commands ###
